language: haskell

branches:
  only:
    - master

sudo: required
cache:
  directories:
    - $HOME/.stack/

matrix:
  include:
    - env: GHCVER=head STACK_YAML=stack.yaml
      addons:
        apt:
          sources:
            -hvr-ghc
          packages:
            - ghc-head
  allow_failures:
    - env: GHCVER=head STACK_YAML=stack.yaml

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry wget https://github.com/commercialhaskell/stack/releases/download/v0.1.6.0/stack-0.1.6.0-linux-x86_64.tar.gz
  - tar xzf stack-0.1.6.0-linux-x86_64.tar.gz
  - cd stack-0.1.6.0-linux-x86_64/
  - cp ./stack ~/.local/bin/
  - chmod a+x ~/.local/bin/stack


install:
  - stack --no-terminal --skip-ghc-check setup
  - stack --no-terminal --skip-ghc-check build

script:
  - stack --no-terminal --skip-ghc-check test
